apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: api-field-test
  title: API Field Test
  description: An template for the scaffolder that creates a Django service
spec:
  owner: bhavya.sinha@harness.io
  type: service
  parameters:
    properties:
    - title: Custom
      properties:
        custom:
          type: string
          ui:field: SelectFieldFromApi
          ui:options:
            title: My Dropdown title
            description: My custom description for the component
            path: proxy/api-workflow
            params:
              facet: kind
            placeholder: Select from options
            arraySelector: facets.kind
            valueSelector: value
            labelSelector: value
  steps:
    - id: trigger
      name: Creating Your Django Service
      action: trigger:harness-custom-pipeline
      input:
        url: https://stress.harness.io/ng/account/zEaak-FLS425IEO7OLzMUg/module/home/orgs/default/projects/projctidp/pipelines/citestpipeline/pipeline-studio?storeType=INLINE
