apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: grafana
  description: pipeline build and deploy
  annotations:
    harness.io/project-url: https://uat.harness.io/ng/account/I3TdrVLBSd2Zr2ttor7Z2A/cf/orgs/default/projects/HarnessFeatureFlags/
    grafana/dashboard-selector: "folderUrl == 'https://grafana.harness.io/dashboards/f/X3UO7QLVk/sto' || folderUrl == 'https://grafana.harness.io/dashboards/f/3oaJ5P94z/cie'"
    grafana/alert-label-selector: "service=chaos-driver-alerts-prod1"
    grafana/overview-dashboard: "https://grafana.harness.io/d/-zsEc0J4k/sto-core-and-ticket-service?orgId=1"

  tags:
    - java

  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
spec:
  type: service
  lifecycle: experimental
  owner: team-cme
